/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metodos.metodos;

/**
 *
 * @author Juanma
 */
public class Registrar extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        try {
            initComponents();
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM especialidades";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String especialidad = rs.getString("nombre");
                EspecialidadComboBox.addItem(especialidad);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEspecialidad = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        EspecialidadComboBox = new javax.swing.JComboBox<>();
        AceptarEspecialidadButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UsuarioTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TlfTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SalarioTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ApellidosTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        CargoComboBox = new javax.swing.JComboBox<>();
        RegistrarButton = new javax.swing.JButton();

        jDialogEspecialidad.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialogEspecialidad.setResizable(false);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel9.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("elija una especialidad");

        AceptarEspecialidadButton.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        AceptarEspecialidadButton.setText("Aceptar");
        AceptarEspecialidadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarEspecialidadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(EspecialidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(AceptarEspecialidadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addComponent(EspecialidadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(AceptarEspecialidadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jDialogEspecialidadLayout = new javax.swing.GroupLayout(jDialogEspecialidad.getContentPane());
        jDialogEspecialidad.getContentPane().setLayout(jDialogEspecialidadLayout);
        jDialogEspecialidadLayout.setHorizontalGroup(
            jDialogEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogEspecialidadLayout.setVerticalGroup(
            jDialogEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(532, 636));
        setMinimumSize(new java.awt.Dimension(532, 636));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(532, 636));
        jPanel1.setMinimumSize(new java.awt.Dimension(532, 636));
        jPanel1.setPreferredSize(new java.awt.Dimension(532, 636));

        jLabel1.setFont(new java.awt.Font("Storm Gust", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(532, 540));
        jPanel2.setMinimumSize(new java.awt.Dimension(532, 540));
        jPanel2.setPreferredSize(new java.awt.Dimension(532, 540));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");
        jPanel2.add(jLabel2);
        jPanel2.add(UsuarioTextField);

        jLabel3.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Número de teléfono:");
        jPanel2.add(jLabel3);
        jPanel2.add(TlfTextField);

        jLabel4.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Salario:");
        jPanel2.add(jLabel4);
        jPanel2.add(SalarioTextField);

        jLabel5.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5);
        jPanel2.add(NombreTextField);

        jLabel6.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Apellidos:");
        jPanel2.add(jLabel6);
        jPanel2.add(ApellidosTextField);

        jLabel7.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña:");
        jPanel2.add(jLabel7);
        jPanel2.add(PasswordTextField);

        jLabel8.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cargo:");
        jPanel2.add(jLabel8);

        CargoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visitante", "Administrador", "Cuidador" }));
        jPanel2.add(CargoComboBox);

        RegistrarButton.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        RegistrarButton.setForeground(new java.awt.Color(0, 0, 0));
        RegistrarButton.setText("Registrar");
        RegistrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegistrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RegistrarButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarButtonActionPerformed
 
        String usuario = UsuarioTextField.getText();
        String telefono = TlfTextField.getText();
        String sal = SalarioTextField.getText();
        String nombre = NombreTextField.getText();
        String apellidos = ApellidosTextField.getText();
        String pass = metodos.passMD5(PasswordTextField.getText());
        String cargo = CargoComboBox.getSelectedItem().toString();
        
        if(UsuarioTextField.getText() == "" || TlfTextField.getText() == "" || SalarioTextField.getText() == "" || NombreTextField.getText() == "" || ApellidosTextField.getText() == "" || PasswordTextField.getText() == ""){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        }else if(metodos.validarMovil(telefono) == false){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir un número de telefono válido");
            TlfTextField.setText("");
        }else if(metodos.isNumeric(sal) == false){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir un salario válido");
            SalarioTextField.setText("");
        }else{
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = (Connection) c.makeConnect();
            if (cargo == "Cuidador") {
                jDialogEspecialidad.setVisible(true);
            }else{
                
                try{
                    float salario = Float.parseFloat(sal);
                    int tlf = Integer.parseInt(telefono);
                    Statement st = conn.createStatement();
                    String sql = metodos.insertarPersonas(usuario, tlf, salario, nombre, apellidos, cargo, pass);
                    System.out.println(sql);
                    int resultado = st.executeUpdate(sql);
                    
                    if (resultado > 0) {
                        
                        JOptionPane.showMessageDialog(null, "Persona registrada correctamente");
                        this.dispose();
                        Login open = new Login();
                        open.setVisible(true);
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Ha habido un error registrando a la persona, prueba de nuevo");
                        UsuarioTextField.setText("");
                        TlfTextField.setText("");
                        SalarioTextField.setText("");
                        NombreTextField.setText("");
                        ApellidosTextField.setText("");
                        PasswordTextField.setText("");
                    }

                }catch(SQLException e){
                    e.toString();
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_RegistrarButtonActionPerformed

    private void AceptarEspecialidadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarEspecialidadButtonActionPerformed
        try {
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            String usuario = UsuarioTextField.getText();
            String telefono = TlfTextField.getText();
            String sal = SalarioTextField.getText();
            String nombre = NombreTextField.getText();
            String apellidos = ApellidosTextField.getText();
            String cargo = CargoComboBox.getSelectedItem().toString();
            String pass = metodos.passMD5(PasswordTextField.getText());
            String especialidad = EspecialidadComboBox.getSelectedItem().toString();
            
            float salario = Float.parseFloat(sal);
            int tlf = Integer.parseInt(telefono);
            Statement st = conn.createStatement(); 
            String sql = metodos.insertarCuidador(usuario, tlf, salario, nombre, apellidos, cargo, especialidad, pass);
            int resultado = st.executeUpdate(sql);
            
            if (resultado > 0) {
                
                JOptionPane.showMessageDialog(null, "Persona registrada correctamente");
                this.dispose();
                Login open = new Login();
                open.setVisible(true);
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Ha habido un error registrando a la persona, prueba de nuevo");
                UsuarioTextField.setText("");
                TlfTextField.setText("");
                SalarioTextField.setText("");
                NombreTextField.setText("");
                ApellidosTextField.setText("");
                PasswordTextField.setText("");
                Registrar open = new Registrar();
                open.setVisible(true);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_AceptarEspecialidadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarEspecialidadButton;
    private javax.swing.JTextField ApellidosTextField;
    private javax.swing.JComboBox<String> CargoComboBox;
    private javax.swing.JComboBox<String> EspecialidadComboBox;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JButton RegistrarButton;
    private javax.swing.JTextField SalarioTextField;
    private javax.swing.JTextField TlfTextField;
    private javax.swing.JTextField UsuarioTextField;
    private javax.swing.JDialog jDialogEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
