/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Login.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.metodos;

/**
 *
 * @author Juanma
 */
public class Animales extends javax.swing.JFrame {

    private int x, y;

    public Animales() {
        try {
            initComponents();
            Conexion c = new Conexion("servidor.choto.es", "3306", "alu_Juanma_zoo1", "unalumno", "soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM animales";
            ResultSet rs = st.executeQuery(sql);
            DefaultTableModel tabla = (DefaultTableModel) TablaAnimales.getModel();

            while (tabla.getRowCount() > 0) {
                tabla.removeRow(0);
            }

            while (rs.next()) {

                tabla.addRow(new Object[]{rs.getInt("id"), rs.getString("nombre"), rs.getString("raza"),
                    rs.getString("genero")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(Animales.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddAnimal = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NombreATextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RazaTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        BarraCerrar = new javax.swing.JPanel();
        LabelCerrar = new javax.swing.JLabel();
        LabelAceptar = new javax.swing.JLabel();
        jDialogEditarAnimal = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NombreATextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RazaTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxGenero1 = new javax.swing.JComboBox<>();
        BarraCerrar2 = new javax.swing.JPanel();
        LabelCerrar2 = new javax.swing.JLabel();
        LabelAceptar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAnimales = new javax.swing.JTable();
        AddAnimalButton = new javax.swing.JButton();
        EliminarAnimalButton = new javax.swing.JButton();
        ModificarAnimalButton = new javax.swing.JButton();
        BarraCerrar1 = new javax.swing.JPanel();
        LabelCerrar1 = new javax.swing.JLabel();

        jDialogAddAnimal.setMinimumSize(new java.awt.Dimension(690, 395));
        jDialogAddAnimal.setUndecorated(true);
        jDialogAddAnimal.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(690, 395));
        jPanel2.setMinimumSize(new java.awt.Dimension(690, 395));

        jLabel2.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("añadir animal");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        jPanel3.add(jLabel4);
        jPanel3.add(NombreATextField);

        jLabel5.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("raza:");
        jPanel3.add(jLabel5);
        jPanel3.add(RazaTextField);

        jLabel6.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("genero:");
        jPanel3.add(jLabel6);

        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel3.add(ComboBoxGenero);

        BarraCerrar.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrarMouseDragged(evt);
            }
        });
        BarraCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrarMousePressed(evt);
            }
        });

        LabelCerrar.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar.setText("x");
        LabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseClicked(evt);
            }
        });

        LabelAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrarLayout = new javax.swing.GroupLayout(BarraCerrar);
        BarraCerrar.setLayout(BarraCerrarLayout);
        BarraCerrarLayout.setHorizontalGroup(
            BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelCerrar)
                .addGap(26, 26, 26))
        );
        BarraCerrarLayout.setVerticalGroup(
            BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCerrar)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(BarraCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BarraCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAddAnimalLayout = new javax.swing.GroupLayout(jDialogAddAnimal.getContentPane());
        jDialogAddAnimal.getContentPane().setLayout(jDialogAddAnimalLayout);
        jDialogAddAnimalLayout.setHorizontalGroup(
            jDialogAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogAddAnimalLayout.setVerticalGroup(
            jDialogAddAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialogEditarAnimal.setMaximumSize(new java.awt.Dimension(690, 395));
        jDialogEditarAnimal.setMinimumSize(new java.awt.Dimension(690, 395));
        jDialogEditarAnimal.setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(690, 395));
        jPanel4.setMinimumSize(new java.awt.Dimension(690, 395));

        jLabel3.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("editar animal");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel7.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre:");
        jPanel5.add(jLabel7);
        jPanel5.add(NombreATextField1);

        jLabel8.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("raza:");
        jPanel5.add(jLabel8);
        jPanel5.add(RazaTextField1);

        jLabel9.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("genero:");
        jPanel5.add(jLabel9);

        ComboBoxGenero1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel5.add(ComboBoxGenero1);

        BarraCerrar2.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar2MouseDragged(evt);
            }
        });
        BarraCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar2MousePressed(evt);
            }
        });

        LabelCerrar2.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar2.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar2.setText("x");
        LabelCerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar2MouseClicked(evt);
            }
        });

        LabelAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelAceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar2Layout = new javax.swing.GroupLayout(BarraCerrar2);
        BarraCerrar2.setLayout(BarraCerrar2Layout);
        BarraCerrar2Layout.setHorizontalGroup(
            BarraCerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelCerrar2)
                .addGap(26, 26, 26))
        );
        BarraCerrar2Layout.setVerticalGroup(
            BarraCerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCerrar2)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(BarraCerrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BarraCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEditarAnimalLayout = new javax.swing.GroupLayout(jDialogEditarAnimal.getContentPane());
        jDialogEditarAnimal.getContentPane().setLayout(jDialogEditarAnimalLayout);
        jDialogEditarAnimalLayout.setHorizontalGroup(
            jDialogEditarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogEditarAnimalLayout.setVerticalGroup(
            jDialogEditarAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 395));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 463));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 463));

        jLabel1.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Animales");

        TablaAnimales.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TablaAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Raza", "Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaAnimales);

        AddAnimalButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        AddAnimalButton.setText("Añadir animal");
        AddAnimalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAnimalButtonActionPerformed(evt);
            }
        });

        EliminarAnimalButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        EliminarAnimalButton.setText("Eliminar animal");
        EliminarAnimalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAnimalButtonActionPerformed(evt);
            }
        });

        ModificarAnimalButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        ModificarAnimalButton.setText("Modificar animal");
        ModificarAnimalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarAnimalButtonActionPerformed(evt);
            }
        });

        BarraCerrar1.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar1MouseDragged(evt);
            }
        });
        BarraCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar1MousePressed(evt);
            }
        });

        LabelCerrar1.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar1.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar1.setText("x");
        LabelCerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar1Layout = new javax.swing.GroupLayout(BarraCerrar1);
        BarraCerrar1.setLayout(BarraCerrar1Layout);
        BarraCerrar1Layout.setHorizontalGroup(
            BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar1)
                .addGap(26, 26, 26))
        );
        BarraCerrar1Layout.setVerticalGroup(
            BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(ModificarAnimalButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EliminarAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(BarraCerrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddAnimalButton, EliminarAnimalButton, ModificarAnimalButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarraCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarAnimalButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddAnimalButton, EliminarAnimalButton, ModificarAnimalButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar1MouseClicked

        this.dispose();
    }//GEN-LAST:event_LabelCerrar1MouseClicked

    private void BarraCerrar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar1MouseDragged
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_BarraCerrar1MouseDragged

    private void BarraCerrar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar1MousePressed

    private void LabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseClicked
        jDialogAddAnimal.setVisible(false);
    }//GEN-LAST:event_LabelCerrarMouseClicked

    private void LabelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptarMouseClicked

        if (NombreATextField.getText() == "" || RazaTextField.getText() == "") {
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        } else {
            try {
                Conexion c = new Conexion("servidor.choto.es", "3306", "alu_Juanma_zoo1", "unalumno", "soyunalumno2022");
                Connection conn = c.makeConnect();
                String nombre = NombreATextField.getText();
                String raza = RazaTextField.getText();
                String genero = ComboBoxGenero.getSelectedItem().toString();
                Statement st = conn.createStatement();
                String sql = "INSERT INTO animales VALUES (null,'" + nombre + "','" + raza + "','" + genero + "',current_timestamp())";
                int resultado = st.executeUpdate(sql);

                if (resultado > 0) {

                    sql = "SELECT * FROM animales";
                    ResultSet rs = st.executeQuery(sql);
                    DefaultTableModel tabla = (DefaultTableModel) TablaAnimales.getModel();

                    while (tabla.getRowCount() > 0) {
                        tabla.removeRow(0);
                    }

                    while (rs.next()) {

                        tabla.addRow(new Object[]{rs.getInt("id"), rs.getString("nombre"), rs.getString("raza"),
                            rs.getString("genero")});

                    }
                    JOptionPane.showMessageDialog(null, "Animal registrado correctamente");
                    jDialogAddAnimal.dispose();

                } else {

                    JOptionPane.showMessageDialog(null, "Ha habido un error registrando al animal, prueba de nuevo");
                    NombreATextField.setText("");
                    RazaTextField.setText("");

                }

            } catch (SQLException ex) {
                Logger.getLogger(Animales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_LabelAceptarMouseClicked

    private void BarraCerrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrarMouseDragged
        jDialogAddAnimal.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_BarraCerrarMouseDragged

    private void BarraCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrarMousePressed

    private void AddAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAnimalButtonActionPerformed
        jDialogAddAnimal.setVisible(true);
    }//GEN-LAST:event_AddAnimalButtonActionPerformed

    private void LabelCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar2MouseClicked
        jDialogEditarAnimal.setVisible(false);
    }//GEN-LAST:event_LabelCerrar2MouseClicked

    private void LabelAceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptar1MouseClicked
        if (NombreATextField1.getText() == "" || RazaTextField1.getText() == "") {
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        } else {
            try {
                Conexion c = new Conexion("servidor.choto.es", "3306", "alu_Juanma_zoo1", "unalumno", "soyunalumno2022");
                Connection conn = c.makeConnect();
                DefaultTableModel tabla = (DefaultTableModel) TablaAnimales.getModel();
                String id = String.valueOf(tabla.getValueAt(TablaAnimales.getSelectedRow(), 0));
                String nombre = NombreATextField1.getText();
                String raza = RazaTextField1.getText();
                String genero = ComboBoxGenero1.getSelectedItem().toString();

                Statement st = conn.createStatement();
                String sql = "UPDATE animales SET nombre='" + nombre + "',raza='" + raza + "',genero='" + genero + "' WHERE id=" + id;

                int resultado = st.executeUpdate(sql);

                if (resultado > 0) {

                    sql = "SELECT * FROM animales";
                    ResultSet rs = st.executeQuery(sql);

                    while (tabla.getRowCount() > 0) {
                        tabla.removeRow(0);
                    }

                    while (rs.next()) {

                        tabla.addRow(new Object[]{rs.getInt("id"), rs.getString("nombre"), rs.getString("raza"),
                            rs.getString("genero")});

                    }
                    JOptionPane.showMessageDialog(null, "Animal editado correctamente");
                    jDialogEditarAnimal.dispose();

                } else {

                    JOptionPane.showMessageDialog(null, "Ha habido un error editando al animal, prueba de nuevo");
                    NombreATextField.setText("");
                    RazaTextField.setText("");

                }

            } catch (SQLException ex) {
                Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_LabelAceptar1MouseClicked

    private void BarraCerrar2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar2MouseDragged
        jDialogEditarAnimal.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_BarraCerrar2MouseDragged

    private void BarraCerrar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar2MousePressed

    private void ModificarAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarAnimalButtonActionPerformed
        if (TablaAnimales.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes seleccionar 1 fila");
        } else {

            DefaultTableModel tabla = (DefaultTableModel) TablaAnimales.getModel();
            String nombre = String.valueOf(tabla.getValueAt(TablaAnimales.getSelectedRow(), 1));
            String raza = String.valueOf(tabla.getValueAt(TablaAnimales.getSelectedRow(), 2));
            NombreATextField1.setText(nombre);
            RazaTextField1.setText(String.valueOf(raza));

            jDialogEditarAnimal.setVisible(true);

        }
    }//GEN-LAST:event_ModificarAnimalButtonActionPerformed

    private void EliminarAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAnimalButtonActionPerformed
        try {
            DefaultTableModel tabla = (DefaultTableModel) TablaAnimales.getModel();
            int id = (int) tabla.getValueAt(TablaAnimales.getSelectedRow(), 0);
            String stringId = String.valueOf(id);
            String sql = "DELETE FROM animales WHERE id=" + stringId;
            Conexion c = new Conexion("servidor.choto.es", "3306", "alu_Juanma_zoo1", "unalumno", "soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            int resultado = st.executeUpdate(sql);
            if (resultado > 0) {
                tabla.removeRow(TablaAnimales.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Se ha eliminado al animal exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "No se ha podido eliminar al animal");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EliminarAnimalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAnimalButton;
    private javax.swing.JPanel BarraCerrar;
    private javax.swing.JPanel BarraCerrar1;
    private javax.swing.JPanel BarraCerrar2;
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JComboBox<String> ComboBoxGenero1;
    private javax.swing.JButton EliminarAnimalButton;
    private javax.swing.JLabel LabelAceptar;
    private javax.swing.JLabel LabelAceptar1;
    private javax.swing.JLabel LabelCerrar;
    private javax.swing.JLabel LabelCerrar1;
    private javax.swing.JLabel LabelCerrar2;
    private javax.swing.JButton ModificarAnimalButton;
    private javax.swing.JTextField NombreATextField;
    private javax.swing.JTextField NombreATextField1;
    private javax.swing.JTextField RazaTextField;
    private javax.swing.JTextField RazaTextField1;
    private javax.swing.JTable TablaAnimales;
    private javax.swing.JDialog jDialogAddAnimal;
    private javax.swing.JDialog jDialogEditarAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
