/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Login.Conexion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author Juanma
 */
public class Especialidades extends javax.swing.JFrame {

    private int x,y;
    
    public Especialidades() {
        try {
            initComponents();
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM especialidades";
            ResultSet rs = st.executeQuery(sql);
            DefaultTableModel tabla = (DefaultTableModel) TablaEspecialidades.getModel();
            
            while(tabla.getRowCount()>0){
                tabla.removeRow(0);
            }
            
            while(rs.next()){
                    
                tabla.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("descripcion")});
  
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddEspecialidad = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DescripcionTextField = new javax.swing.JTextField();
        BarraCerrar = new javax.swing.JPanel();
        LabelCerrar = new javax.swing.JLabel();
        LabelAceptar = new javax.swing.JLabel();
        jDialogEditarEspecialidad = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NombreTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DescripcionTextField1 = new javax.swing.JTextField();
        BarraCerrar2 = new javax.swing.JPanel();
        LabelCerrar2 = new javax.swing.JLabel();
        LabelAceptar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEspecialidades = new javax.swing.JTable();
        AddEspecialidadButton = new javax.swing.JButton();
        EliminarEspecialidadButton = new javax.swing.JButton();
        ModificarEspecialidadButton = new javax.swing.JButton();
        BarraCerrar14 = new javax.swing.JPanel();
        LabelCerrar14 = new javax.swing.JLabel();

        jDialogAddEspecialidad.setMinimumSize(new java.awt.Dimension(690, 395));
        jDialogAddEspecialidad.setUndecorated(true);
        jDialogAddEspecialidad.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(690, 395));
        jPanel2.setMinimumSize(new java.awt.Dimension(690, 395));

        jLabel2.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("añadir Especialidad");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        jPanel3.add(jLabel4);
        jPanel3.add(NombreTextField);

        jLabel5.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descripción:");
        jPanel3.add(jLabel5);
        jPanel3.add(DescripcionTextField);

        BarraCerrar.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrarMouseDragged(evt);
            }
        });
        BarraCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrarMousePressed(evt);
            }
        });

        LabelCerrar.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar.setText("x");
        LabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseClicked(evt);
            }
        });

        LabelAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrarLayout = new javax.swing.GroupLayout(BarraCerrar);
        BarraCerrar.setLayout(BarraCerrarLayout);
        BarraCerrarLayout.setHorizontalGroup(
            BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelCerrar)
                .addGap(26, 26, 26))
        );
        BarraCerrarLayout.setVerticalGroup(
            BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCerrar)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(BarraCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BarraCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAddEspecialidadLayout = new javax.swing.GroupLayout(jDialogAddEspecialidad.getContentPane());
        jDialogAddEspecialidad.getContentPane().setLayout(jDialogAddEspecialidadLayout);
        jDialogAddEspecialidadLayout.setHorizontalGroup(
            jDialogAddEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogAddEspecialidadLayout.setVerticalGroup(
            jDialogAddEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialogEditarEspecialidad.setMinimumSize(new java.awt.Dimension(690, 395));
        jDialogEditarEspecialidad.setUndecorated(true);
        jDialogEditarEspecialidad.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(690, 395));
        jPanel4.setMinimumSize(new java.awt.Dimension(690, 395));

        jLabel3.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("editar especialidad");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel7.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombre:");
        jPanel5.add(jLabel7);
        jPanel5.add(NombreTextField1);

        jLabel8.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Descripción:");
        jPanel5.add(jLabel8);
        jPanel5.add(DescripcionTextField1);

        BarraCerrar2.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar2MouseDragged(evt);
            }
        });
        BarraCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar2MousePressed(evt);
            }
        });

        LabelCerrar2.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar2.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar2.setText("x");
        LabelCerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar2MouseClicked(evt);
            }
        });

        LabelAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelAceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar2Layout = new javax.swing.GroupLayout(BarraCerrar2);
        BarraCerrar2.setLayout(BarraCerrar2Layout);
        BarraCerrar2Layout.setHorizontalGroup(
            BarraCerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelCerrar2)
                .addGap(26, 26, 26))
        );
        BarraCerrar2Layout.setVerticalGroup(
            BarraCerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCerrar2)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(BarraCerrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BarraCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEditarEspecialidadLayout = new javax.swing.GroupLayout(jDialogEditarEspecialidad.getContentPane());
        jDialogEditarEspecialidad.getContentPane().setLayout(jDialogEditarEspecialidadLayout);
        jDialogEditarEspecialidadLayout.setHorizontalGroup(
            jDialogEditarEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogEditarEspecialidadLayout.setVerticalGroup(
            jDialogEditarEspecialidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 463));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 463));

        jLabel1.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("especialidades");

        TablaEspecialidades.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TablaEspecialidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaEspecialidades);

        AddEspecialidadButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        AddEspecialidadButton.setText("Añadir Especialidad");
        AddEspecialidadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEspecialidadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEspecialidadButtonActionPerformed(evt);
            }
        });

        EliminarEspecialidadButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        EliminarEspecialidadButton.setText("Eliminar Especialidad");
        EliminarEspecialidadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarEspecialidadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEspecialidadButtonActionPerformed(evt);
            }
        });

        ModificarEspecialidadButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        ModificarEspecialidadButton.setText("modificar especialidad");
        ModificarEspecialidadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarEspecialidadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEspecialidadButtonActionPerformed(evt);
            }
        });

        BarraCerrar14.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar14MouseDragged(evt);
            }
        });
        BarraCerrar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar14MousePressed(evt);
            }
        });

        LabelCerrar14.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar14.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar14.setText("x");
        LabelCerrar14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar14Layout = new javax.swing.GroupLayout(BarraCerrar14);
        BarraCerrar14.setLayout(BarraCerrar14Layout);
        BarraCerrar14Layout.setHorizontalGroup(
            BarraCerrar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar14)
                .addGap(26, 26, 26))
        );
        BarraCerrar14Layout.setVerticalGroup(
            BarraCerrar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddEspecialidadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModificarEspecialidadButton)
                .addGap(76, 76, 76)
                .addComponent(EliminarEspecialidadButton)
                .addGap(28, 28, 28))
            .addComponent(BarraCerrar14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddEspecialidadButton, EliminarEspecialidadButton, ModificarEspecialidadButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarraCerrar14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEspecialidadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarEspecialidadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarEspecialidadButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddEspecialidadButton, EliminarEspecialidadButton, ModificarEspecialidadButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCerrar14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar14MouseClicked

        this.dispose();
    }//GEN-LAST:event_LabelCerrar14MouseClicked

    private void BarraCerrar14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar14MouseDragged
        this.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrar14MouseDragged

    private void BarraCerrar14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar14MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar14MousePressed

    private void AddEspecialidadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEspecialidadButtonActionPerformed
        jDialogAddEspecialidad.setVisible(true);
    }//GEN-LAST:event_AddEspecialidadButtonActionPerformed

    private void ModificarEspecialidadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEspecialidadButtonActionPerformed
        if (TablaEspecialidades.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes seleccionar 1 fila");
        }else{

            DefaultTableModel tabla = (DefaultTableModel) TablaEspecialidades.getModel();
            String nombre = String.valueOf(tabla.getValueAt(TablaEspecialidades.getSelectedRow(), 1));
            String raza = String.valueOf(tabla.getValueAt(TablaEspecialidades.getSelectedRow(), 2));
            NombreTextField1.setText(nombre);
            DescripcionTextField1.setText(String.valueOf(raza));
      
            jDialogEditarEspecialidad.setVisible(true);
            
        }
    }//GEN-LAST:event_ModificarEspecialidadButtonActionPerformed

    private void LabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseClicked
        jDialogAddEspecialidad.setVisible(false);
    }//GEN-LAST:event_LabelCerrarMouseClicked

    private void LabelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptarMouseClicked

        if(NombreTextField.getText() == "" || DescripcionTextField.getText() == ""){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        }else{
            try {
                Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
                Connection conn = c.makeConnect();
                String nombre = NombreTextField.getText();
                String descripcion = DescripcionTextField.getText();
                Statement st = conn.createStatement();

                String sql = "INSERT INTO especialidades VALUES (null,'"+nombre+"','"+descripcion+"',current_timestamp())";
                int resultado = st.executeUpdate(sql);

                if (resultado > 0) {

                    sql = "SELECT * FROM especialidades";
                    ResultSet rs = st.executeQuery(sql);
                    DefaultTableModel tabla = (DefaultTableModel) TablaEspecialidades.getModel();

                    while(tabla.getRowCount()>0){
                        tabla.removeRow(0);
                    }

                    while(rs.next()){

                        tabla.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("descripcion")});

                    }
                    JOptionPane.showMessageDialog(null, "Especialidad registrada correctamente");
                    jDialogAddEspecialidad.dispose();

                }else{

                    JOptionPane.showMessageDialog(null, "Ha habido un error registrando la especialidad, prueba de nuevo");
                    NombreTextField.setText("");
                    DescripcionTextField.setText("");

                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_LabelAceptarMouseClicked

    private void BarraCerrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrarMouseDragged
        jDialogAddEspecialidad.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrarMouseDragged

    private void BarraCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrarMousePressed

    private void LabelCerrar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar2MouseClicked
        jDialogEditarEspecialidad.setVisible(false);
    }//GEN-LAST:event_LabelCerrar2MouseClicked

    private void LabelAceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptar1MouseClicked
        if(NombreTextField1.getText() == "" || DescripcionTextField1.getText() == ""){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        }else{
            try {
                Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
                Connection conn = c.makeConnect();
                DefaultTableModel tabla = (DefaultTableModel) TablaEspecialidades.getModel();
                String id = String.valueOf(tabla.getValueAt(TablaEspecialidades.getSelectedRow(), 0));
                String nombre = NombreTextField1.getText();
                String descripcion = DescripcionTextField1.getText();

                Statement st = conn.createStatement();
                String sql = "UPDATE especialidades SET nombre='"+nombre+"',descripcion='"+descripcion+"' WHERE id="+id;

                int resultado = st.executeUpdate(sql);

                if (resultado > 0) {

                    sql = "SELECT * FROM especialidades";
                    ResultSet rs = st.executeQuery(sql);

                    while(tabla.getRowCount()>0){
                        tabla.removeRow(0);
                    }

                    while(rs.next()){

                        tabla.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("descripcion")});

                    }
                    JOptionPane.showMessageDialog(null, "Especialidad editada correctamente");
                    jDialogEditarEspecialidad.dispose();

                }else{

                    JOptionPane.showMessageDialog(null, "Ha habido un error editando la especialidad, prueba de nuevo");
                    NombreTextField1.setText("");
                    DescripcionTextField1.setText("");

                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_LabelAceptar1MouseClicked

    private void BarraCerrar2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar2MouseDragged
        jDialogEditarEspecialidad.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrar2MouseDragged

    private void BarraCerrar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar2MousePressed

    private void EliminarEspecialidadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEspecialidadButtonActionPerformed
        
        try {
            DefaultTableModel tabla = (DefaultTableModel) TablaEspecialidades.getModel();
            int id = (int) tabla.getValueAt(TablaEspecialidades.getSelectedRow(), 0);
            String stringId = String.valueOf(id);
            String sql = "DELETE FROM especialidades WHERE id="+stringId;
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            int resultado = st.executeUpdate(sql);
            if (resultado > 0) {
                tabla.removeRow(TablaEspecialidades.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Se ha eliminado el cuidado exitosamente");
            }else{
                JOptionPane.showMessageDialog(null, "No se ha podido eliminar el cuidado");
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Cuidados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EliminarEspecialidadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Especialidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Especialidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEspecialidadButton;
    private javax.swing.JPanel BarraCerrar;
    private javax.swing.JPanel BarraCerrar14;
    private javax.swing.JPanel BarraCerrar2;
    private javax.swing.JTextField DescripcionTextField;
    private javax.swing.JTextField DescripcionTextField1;
    private javax.swing.JButton EliminarEspecialidadButton;
    private javax.swing.JLabel LabelAceptar;
    private javax.swing.JLabel LabelAceptar1;
    private javax.swing.JLabel LabelCerrar;
    private javax.swing.JLabel LabelCerrar14;
    private javax.swing.JLabel LabelCerrar2;
    private javax.swing.JButton ModificarEspecialidadButton;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JTextField NombreTextField1;
    private javax.swing.JTable TablaEspecialidades;
    private javax.swing.JDialog jDialogAddEspecialidad;
    private javax.swing.JDialog jDialogEditarEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
