/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import metodos.*;
import Login.*;
/**
 *
 * @author Juanma
 */
public class Menu_admin extends javax.swing.JFrame {
    
    private int x,y;
    /**
     * Creates new form Menu_admin
     */
    public Menu_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Tareas = new javax.swing.JButton();
        EspecialidadesButton = new javax.swing.JButton();
        VolverLoginButton = new javax.swing.JButton();
        CuidadosButton = new javax.swing.JButton();
        AnimalesButton = new javax.swing.JButton();
        TrabajadoresButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        BarraCerrar1 = new javax.swing.JPanel();
        LabelCerrar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 300));
        setMinimumSize(new java.awt.Dimension(550, 300));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(550, 237));
        jPanel1.setMinimumSize(new java.awt.Dimension(550, 237));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 300));

        jLabel1.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido!");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(200, 335));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 335));
        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setMaximumSize(new java.awt.Dimension(200, 335));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 335));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        Tareas.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        Tareas.setText("Tareas");
        Tareas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TareasActionPerformed(evt);
            }
        });

        EspecialidadesButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        EspecialidadesButton.setText("Especialidades");
        EspecialidadesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EspecialidadesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadesButtonActionPerformed(evt);
            }
        });

        VolverLoginButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        VolverLoginButton.setText("Volver al Login");
        VolverLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolverLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverLoginButtonActionPerformed(evt);
            }
        });

        CuidadosButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        CuidadosButton.setText("Cuidados");
        CuidadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CuidadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuidadosButtonActionPerformed(evt);
            }
        });

        AnimalesButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        AnimalesButton.setText("Animales");
        AnimalesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AnimalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalesButtonActionPerformed(evt);
            }
        });

        TrabajadoresButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        TrabajadoresButton.setText("Trabajadores");
        TrabajadoresButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TrabajadoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrabajadoresButtonActionPerformed(evt);
            }
        });

        SalirButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        SalirButton.setText("Salir");
        SalirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        BarraCerrar1.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar1MouseDragged(evt);
            }
        });
        BarraCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar1MousePressed(evt);
            }
        });

        LabelCerrar1.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar1.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar1.setText("x");
        LabelCerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar1Layout = new javax.swing.GroupLayout(BarraCerrar1);
        BarraCerrar1.setLayout(BarraCerrar1Layout);
        BarraCerrar1Layout.setHorizontalGroup(
            BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar1)
                .addGap(26, 26, 26))
        );
        BarraCerrar1Layout.setVerticalGroup(
            BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrabajadoresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnimalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CuidadosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tareas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EspecialidadesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(SalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(BarraCerrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarraCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Tareas)
                        .addGap(0, 0, 0)
                        .addComponent(EspecialidadesButton)
                        .addGap(0, 0, 0)
                        .addComponent(VolverLoginButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TrabajadoresButton)
                        .addGap(0, 0, 0)
                        .addComponent(AnimalesButton)
                        .addGap(0, 0, 0)
                        .addComponent(CuidadosButton)))
                .addGap(32, 32, 32)
                .addComponent(SalirButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void VolverLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverLoginButtonActionPerformed
        Login open = new Login();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverLoginButtonActionPerformed

    private void TrabajadoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrabajadoresButtonActionPerformed
        
        Trabajadores open = new Trabajadores();
        open.setVisible(true);
        
    }//GEN-LAST:event_TrabajadoresButtonActionPerformed

    private void AnimalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalesButtonActionPerformed
        
        Animales open = new Animales();
        open.setVisible(true);
        
    }//GEN-LAST:event_AnimalesButtonActionPerformed

    private void CuidadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuidadosButtonActionPerformed
        
        Cuidados open = new Cuidados();
        open.setVisible(true);
        
    }//GEN-LAST:event_CuidadosButtonActionPerformed

    private void TareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TareasActionPerformed
        
        Tareas open = new Tareas();
        open.setVisible(true);
        
    }//GEN-LAST:event_TareasActionPerformed

    private void EspecialidadesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadesButtonActionPerformed
        
        Especialidades open = new Especialidades();
        open.setVisible(true);
        
    }//GEN-LAST:event_EspecialidadesButtonActionPerformed

    private void LabelCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar1MouseClicked
        
        this.dispose();
        
    }//GEN-LAST:event_LabelCerrar1MouseClicked

    private void BarraCerrar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar1MouseDragged
        this.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrar1MouseDragged

    private void BarraCerrar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnimalesButton;
    private javax.swing.JPanel BarraCerrar1;
    private javax.swing.JButton CuidadosButton;
    private javax.swing.JButton EspecialidadesButton;
    private javax.swing.JLabel LabelCerrar1;
    private javax.swing.JButton SalirButton;
    private javax.swing.JButton Tareas;
    private javax.swing.JButton TrabajadoresButton;
    private javax.swing.JButton VolverLoginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
