/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Login.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juanma
 */
public class Tareas extends javax.swing.JFrame {

    private int x, y;

    public Tareas() {

        try {
            initComponents();
            Conexion c = new Conexion("servidor.choto.es", "3306", "alu_Juanma_zoo1", "unalumno", "soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM personas WHERE cargo='Cuidador'";
            ResultSet rs = st.executeQuery(sql);
            
            
            while (rs.next()) {
                try {

                    String nombreCuidador = rs.getString("nombre");
                    CuidadorComboBox.addItem(nombreCuidador);
                } catch (SQLException ex) {
                    Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            sql = "SELECT * FROM animales";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                try {
                    String nombreAnimal = rs.getString("nombre");
                    AnimalComboBox.addItem(nombreAnimal);
                } catch (SQLException ex) {
                    Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            sql = "SELECT * FROM cuidados";
            rs = st.executeQuery(sql);
                                    
            while (rs.next()) {
                try {
                    String nombreCuidado = rs.getString("nombre");
                    CuidadoComboBox.addItem(nombreCuidado);
                } catch (SQLException ex) {
                    Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            sql = "SELECT * FROM tareas";
            rs = st.executeQuery(sql);
            DefaultTableModel tabla = (DefaultTableModel) TablaTareas.getModel();
            
            
            while (tabla.getRowCount() > 0) {
                tabla.removeRow(0);
            }

            while (rs.next()) {

                String sqlCuidador = "SELECT * FROM personas WHERE id=" + rs.getInt("id_cuidador");
                String sqlAnimal = "SELECT * FROM animales WHERE id=" + rs.getInt("id_animal");
                String sqlCuidado = "SELECT * FROM cuidados WHERE id=" + rs.getInt("id_cuidado");

                ResultSet rsCuidador = st.executeQuery(sqlCuidador);
                ResultSet rsAnimal = st.executeQuery(sqlAnimal);
                ResultSet rsCuidado = st.executeQuery(sqlCuidado);
                
                tabla.addRow(new Object[]{rs.getString("id"), rsCuidador.getString("nombre"), rsAnimal.getString("nombre"),
                rsCuidado.getString("nombre"), rs.getString("fecha"), rs.getString("hora"),false});

            }
        } catch (SQLException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddTarea = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        BarraCerrar15 = new javax.swing.JPanel();
        LabelCerrar15 = new javax.swing.JLabel();
        LabelAceptar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CuidadorComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        AnimalComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CuidadoComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dateTimePicker1 = new com.github.lgooddatepicker.components.DateTimePicker();
        jDialogEditar = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTareas = new javax.swing.JTable();
        AddTareaButton = new javax.swing.JButton();
        EliminarTareaButton = new javax.swing.JButton();
        ModificarTareaButton = new javax.swing.JButton();
        CompletarTareaButton = new javax.swing.JButton();
        BarraCerrar14 = new javax.swing.JPanel();
        LabelCerrar14 = new javax.swing.JLabel();

        jDialogAddTarea.setMinimumSize(new java.awt.Dimension(560, 460));
        jDialogAddTarea.setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(560, 460));
        jPanel2.setMinimumSize(new java.awt.Dimension(560, 460));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 460));

        BarraCerrar15.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar15MouseDragged(evt);
            }
        });
        BarraCerrar15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar15MousePressed(evt);
            }
        });

        LabelCerrar15.setFont(new java.awt.Font("Storm Gust", 0, 65)); // NOI18N
        LabelCerrar15.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar15.setText("x");
        LabelCerrar15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelCerrar15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar15MouseClicked(evt);
            }
        });

        LabelAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar15Layout = new javax.swing.GroupLayout(BarraCerrar15);
        BarraCerrar15.setLayout(BarraCerrar15Layout);
        BarraCerrar15Layout.setHorizontalGroup(
            BarraCerrar15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar)
                .addGap(47, 47, 47)
                .addComponent(LabelCerrar15)
                .addGap(40, 40, 40))
        );
        BarraCerrar15Layout.setVerticalGroup(
            BarraCerrar15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrar15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LabelCerrar15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LabelAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setText("añadir tarea");
        jLabel2.setFont(new java.awt.Font("Storm Gust", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel3.setFont(new java.awt.Font("Storm Gust", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del cuidador:");
        jPanel3.add(jLabel3);

        jPanel3.add(CuidadorComboBox);

        jLabel4.setFont(new java.awt.Font("Storm Gust", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre del animal:");
        jPanel3.add(jLabel4);

        jPanel3.add(AnimalComboBox);

        jLabel5.setFont(new java.awt.Font("Storm Gust", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre del cuidado:");
        jPanel3.add(jLabel5);

        jPanel3.add(CuidadoComboBox);

        jLabel6.setText("Fecha y hora a la que se va a realizar:");
        jLabel6.setFont(new java.awt.Font("Storm Gust", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jLabel6);
        jPanel3.add(dateTimePicker1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraCerrar15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BarraCerrar15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAddTareaLayout = new javax.swing.GroupLayout(jDialogAddTarea.getContentPane());
        jDialogAddTarea.getContentPane().setLayout(jDialogAddTareaLayout);
        jDialogAddTareaLayout.setHorizontalGroup(
            jDialogAddTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddTareaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogAddTareaLayout.setVerticalGroup(
            jDialogAddTareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddTareaLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEditarLayout = new javax.swing.GroupLayout(jDialogEditar.getContentPane());
        jDialogEditar.getContentPane().setLayout(jDialogEditarLayout);
        jDialogEditarLayout.setHorizontalGroup(
            jDialogEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogEditarLayout.setVerticalGroup(
            jDialogEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 463));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 463));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 463));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("tareas");
        jLabel1.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        TablaTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Cuidador", "Animal", "Cuidado", "Fecha", "Hora", "Terminada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaTareas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(TablaTareas);

        AddTareaButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        AddTareaButton.setText("Añadir tarea");
        AddTareaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddTareaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTareaButtonActionPerformed(evt);
            }
        });

        EliminarTareaButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        EliminarTareaButton.setText("Eliminar tarea");
        EliminarTareaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ModificarTareaButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        ModificarTareaButton.setText("Modificar tarea");
        ModificarTareaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CompletarTareaButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        CompletarTareaButton.setText("tarea completada");
        CompletarTareaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        BarraCerrar14.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar14MouseDragged(evt);
            }
        });
        BarraCerrar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar14MousePressed(evt);
            }
        });

        LabelCerrar14.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar14.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar14.setText("x");
        LabelCerrar14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LabelCerrar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar14Layout = new javax.swing.GroupLayout(BarraCerrar14);
        BarraCerrar14.setLayout(BarraCerrar14Layout);
        BarraCerrar14Layout.setHorizontalGroup(
            BarraCerrar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar14)
                .addGap(26, 26, 26))
        );
        BarraCerrar14Layout.setVerticalGroup(
            BarraCerrar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CompletarTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AddTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(ModificarTareaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addComponent(BarraCerrar14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddTareaButton, EliminarTareaButton, ModificarTareaButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarraCerrar14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CompletarTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarTareaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarTareaButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddTareaButton, EliminarTareaButton, ModificarTareaButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCerrar14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar14MouseClicked
        this.dispose();
    }//GEN-LAST:event_LabelCerrar14MouseClicked

    private void BarraCerrar14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar14MouseDragged
        this.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_BarraCerrar14MouseDragged

    private void BarraCerrar14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar14MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar14MousePressed

    private void LabelCerrar15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar15MouseClicked
        jDialogAddTarea.setVisible(false);
    }//GEN-LAST:event_LabelCerrar15MouseClicked

    private void BarraCerrar15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar15MouseDragged
        jDialogAddTarea.setLocation(evt.getXOnScreen() - x, evt.getYOnScreen() - y);
    }//GEN-LAST:event_BarraCerrar15MouseDragged

    private void BarraCerrar15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar15MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar15MousePressed

    private void LabelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptarMouseClicked

        if (dateTimePicker1.getDatePicker().toString() == "" || dateTimePicker1.getTimePicker().toString() == "") {
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir una fecha y una hora");
        } else {
            try {
                Conexion c = new Conexion("servidor.choto.es", "3306", "alu_Juanma_zoo1", "unalumno", "soyunalumno2022");
                Connection conn = c.makeConnect();
                Statement st = conn.createStatement();
                
                String cuidador = CuidadorComboBox.getSelectedItem().toString();
                String animal = AnimalComboBox.getSelectedItem().toString();
                String cuidado = CuidadoComboBox.getSelectedItem().toString();
                
                String sql = "SELECT * FROM personas WHERE nombre='"+cuidador+"'";
                ResultSet rs = st.executeQuery(sql);
                rs.next();
                int idCuidador = rs.getInt("id");
                
                sql = "SELECT * FROM animales WHERE nombre='"+animal+"'";
                rs = st.executeQuery(sql);
                rs.next();
                int idAnimal = rs.getInt("id");
                
                sql = "SELECT * FROM cuidados WHERE nombre='"+cuidado+"'";
                rs = st.executeQuery(sql);
                rs.next();
                int idCuidado = rs.getInt("id");
                
                
                String fecha = dateTimePicker1.getDatePicker().toString();
                String hora = dateTimePicker1.getTimePicker().toString();

                
                sql = "INSERT INTO tareas VALUES(null," + idCuidador + "," + idAnimal + "," + idCuidado + ",'" + fecha + "','" + hora + "',false,current_timestamp())";
                int resultado = st.executeUpdate(sql);
                
                
                if (resultado > 0) {
                    sql = "SELECT * FROM tareas";
                    rs = st.executeQuery(sql);
                    DefaultTableModel tabla = (DefaultTableModel) TablaTareas.getModel();

                    while (tabla.getRowCount() > 0) {
                        tabla.removeRow(0);
                    }

                    while (rs.next()) {

                        String sqlCuidador = "SELECT * FROM personas WHERE id=" + rs.getInt("id_cuidador");
                        String sqlAnimal = "SELECT * FROM animales WHERE id=" + rs.getInt("id_animal");
                        String sqlCuidado = "SELECT * FROM cuidados WHERE id=" + rs.getInt("id_cuidado");

                        ResultSet rsCuidador = st.executeQuery(sqlCuidador);
                        ResultSet rsAnimal = st.executeQuery(sqlAnimal);
                        ResultSet rsCuidado = st.executeQuery(sqlCuidado);

                        tabla.addRow(new Object[]{rs.getInt("id"), rsCuidador.getString("nombre"), rsAnimal.getString("nombre"),
                        rsCuidado.getString("nombre"), rs.getString("fecha"), rs.getString("hora"),false});

                    }
                    JOptionPane.showMessageDialog(null, "Tarea registrada correctamente");
                    jDialogAddTarea.dispose();
                }

            } catch (SQLException ex) {
                Logger.getLogger(Tareas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_LabelAceptarMouseClicked

    private void AddTareaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTareaButtonActionPerformed
        jDialogAddTarea.setVisible(true);
    }//GEN-LAST:event_AddTareaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTareaButton;
    private javax.swing.JComboBox<String> AnimalComboBox;
    private javax.swing.JPanel BarraCerrar14;
    private javax.swing.JPanel BarraCerrar15;
    private javax.swing.JButton CompletarTareaButton;
    private javax.swing.JComboBox<String> CuidadoComboBox;
    private javax.swing.JComboBox<String> CuidadorComboBox;
    private javax.swing.JButton EliminarTareaButton;
    private javax.swing.JLabel LabelAceptar;
    private javax.swing.JLabel LabelCerrar14;
    private javax.swing.JLabel LabelCerrar15;
    private javax.swing.JButton ModificarTareaButton;
    private javax.swing.JTable TablaTareas;
    private com.github.lgooddatepicker.components.DateTimePicker dateTimePicker1;
    private javax.swing.JDialog jDialogAddTarea;
    private javax.swing.JDialog jDialogEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
