/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Login.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodos.metodos;

/**
 *
 * @author Juanma
 */
public class Trabajadores extends javax.swing.JFrame {
    
    private int x, y;
    /**
     * Creates new form Trabajadores
     */
    public Trabajadores() {
        
        try {
            initComponents();
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM especialidades";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                try {
                    String especialidad = rs.getString("nombre");
                    EspecialidadComboBox.addItem(especialidad);
                    EspecialidadComboBox1.addItem(especialidad);
                } catch (SQLException ex) {
                    Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            sql = "SELECT * FROM personas WHERE cargo='Cuidador'";
            rs = st.executeQuery(sql);
            DefaultTableModel tabla = (DefaultTableModel) TablaTrabajadores.getModel();
            
            while(tabla.getRowCount()>0){
                tabla.removeRow(0);
            }
            
            while(rs.next()){
                
                String salario = String.valueOf(rs.getFloat("salario")) + "€";
                
                tabla.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("apellidos"),
                rs.getInt("telefono"),salario,rs.getString("especialidad")});
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddTrabajador = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        UsuarioTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TelefonoTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SalarioTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NombreTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ApellidosTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EspecialidadComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        BarraCerrar = new javax.swing.JPanel();
        LabelCerrar = new javax.swing.JLabel();
        LabelAceptar = new javax.swing.JLabel();
        jDialogEditarTrabajador = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        UsuarioTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TelefonoTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        SalarioTextField1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        NombreTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ApellidosTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EspecialidadComboBox1 = new javax.swing.JComboBox<>();
        BarraCerrar1 = new javax.swing.JPanel();
        LabelCerrar1 = new javax.swing.JLabel();
        LabelAceptar1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTrabajadores = new javax.swing.JTable();
        AddTrabajadorButton = new javax.swing.JButton();
        EliminarTrabajadorButton = new javax.swing.JButton();
        ModificarTrabajadorButton = new javax.swing.JButton();
        BarraCerrar14 = new javax.swing.JPanel();
        LabelCerrar14 = new javax.swing.JLabel();

        jDialogAddTrabajador.setMinimumSize(new java.awt.Dimension(654, 698));
        jDialogAddTrabajador.setUndecorated(true);
        jDialogAddTrabajador.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(654, 698));
        jPanel2.setMinimumSize(new java.awt.Dimension(654, 698));

        jLabel2.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("añadir trabajador");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("usuario:");
        jPanel3.add(jLabel4);
        jPanel3.add(UsuarioTextField);

        jLabel5.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("telefono:");
        jPanel3.add(jLabel5);
        jPanel3.add(TelefonoTextField);

        jLabel6.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("salario:");
        jPanel3.add(jLabel6);
        jPanel3.add(SalarioTextField);

        jLabel7.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("nombre:");
        jPanel3.add(jLabel7);
        jPanel3.add(NombreTextField);

        jLabel8.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("apellidos:");
        jPanel3.add(jLabel8);
        jPanel3.add(ApellidosTextField);

        jLabel10.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("especialidad:");
        jPanel3.add(jLabel10);

        jPanel3.add(EspecialidadComboBox);

        jLabel11.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("contraseña:");
        jPanel3.add(jLabel11);
        jPanel3.add(PasswordTextField);

        BarraCerrar.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrarMouseDragged(evt);
            }
        });
        BarraCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrarMousePressed(evt);
            }
        });

        LabelCerrar.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar.setText("x");
        LabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarMouseClicked(evt);
            }
        });

        LabelAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrarLayout = new javax.swing.GroupLayout(BarraCerrar);
        BarraCerrar.setLayout(BarraCerrarLayout);
        BarraCerrarLayout.setHorizontalGroup(
            BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelCerrar)
                .addGap(26, 26, 26))
        );
        BarraCerrarLayout.setVerticalGroup(
            BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCerrar)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(BarraCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(BarraCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAddTrabajadorLayout = new javax.swing.GroupLayout(jDialogAddTrabajador.getContentPane());
        jDialogAddTrabajador.getContentPane().setLayout(jDialogAddTrabajadorLayout);
        jDialogAddTrabajadorLayout.setHorizontalGroup(
            jDialogAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogAddTrabajadorLayout.setVerticalGroup(
            jDialogAddTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogEditarTrabajador.setMinimumSize(new java.awt.Dimension(654, 698));
        jDialogEditarTrabajador.setUndecorated(true);
        jDialogEditarTrabajador.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setMaximumSize(new java.awt.Dimension(654, 698));
        jPanel4.setMinimumSize(new java.awt.Dimension(654, 698));

        jLabel3.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("editar trabajador");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel9.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("usuario:");
        jPanel5.add(jLabel9);

        UsuarioTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(UsuarioTextField1);

        jLabel12.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("telefono:");
        jPanel5.add(jLabel12);
        jPanel5.add(TelefonoTextField1);

        jLabel13.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("salario:");
        jPanel5.add(jLabel13);
        jPanel5.add(SalarioTextField1);

        jLabel14.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("nombre:");
        jPanel5.add(jLabel14);
        jPanel5.add(NombreTextField1);

        jLabel15.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("apellidos:");
        jPanel5.add(jLabel15);
        jPanel5.add(ApellidosTextField1);

        jLabel16.setFont(new java.awt.Font("Storm Gust", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("especialidad:");
        jPanel5.add(jLabel16);

        jPanel5.add(EspecialidadComboBox1);

        BarraCerrar1.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar1MouseDragged(evt);
            }
        });
        BarraCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar1MousePressed(evt);
            }
        });

        LabelCerrar1.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar1.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar1.setText("x");
        LabelCerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar1MouseClicked(evt);
            }
        });

        LabelAceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Flat_tick_icon (1).png"))); // NOI18N
        LabelAceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelAceptar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelAceptar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar1Layout = new javax.swing.GroupLayout(BarraCerrar1);
        BarraCerrar1.setLayout(BarraCerrar1Layout);
        BarraCerrar1Layout.setHorizontalGroup(
            BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelCerrar1)
                .addGap(26, 26, 26))
        );
        BarraCerrar1Layout.setVerticalGroup(
            BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BarraCerrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCerrar1)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addComponent(BarraCerrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BarraCerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogEditarTrabajadorLayout = new javax.swing.GroupLayout(jDialogEditarTrabajador.getContentPane());
        jDialogEditarTrabajador.getContentPane().setLayout(jDialogEditarTrabajadorLayout);
        jDialogEditarTrabajadorLayout.setHorizontalGroup(
            jDialogEditarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogEditarTrabajadorLayout.setVerticalGroup(
            jDialogEditarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(690, 464));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(690, 464));
        jPanel1.setMinimumSize(new java.awt.Dimension(690, 464));

        jLabel1.setFont(new java.awt.Font("Storm Gust", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trabajadores");

        TablaTrabajadores.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        TablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellidos", "Telefono", "Salario", "Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaTrabajadores);

        AddTrabajadorButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        AddTrabajadorButton.setText("Añadir trabajador");
        AddTrabajadorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddTrabajadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTrabajadorButtonActionPerformed(evt);
            }
        });

        EliminarTrabajadorButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        EliminarTrabajadorButton.setText("Eliminar trabajador");
        EliminarTrabajadorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarTrabajadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTrabajadorButtonActionPerformed(evt);
            }
        });

        ModificarTrabajadorButton.setFont(new java.awt.Font("Storm Gust", 0, 14)); // NOI18N
        ModificarTrabajadorButton.setText("Modificar trabajador");
        ModificarTrabajadorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarTrabajadorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTrabajadorButtonActionPerformed(evt);
            }
        });

        BarraCerrar14.setBackground(new java.awt.Color(0, 0, 0));
        BarraCerrar14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraCerrar14MouseDragged(evt);
            }
        });
        BarraCerrar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraCerrar14MousePressed(evt);
            }
        });

        LabelCerrar14.setFont(new java.awt.Font("Storm Gust", 0, 56)); // NOI18N
        LabelCerrar14.setForeground(new java.awt.Color(204, 204, 204));
        LabelCerrar14.setText("x");
        LabelCerrar14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelCerrar14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrar14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BarraCerrar14Layout = new javax.swing.GroupLayout(BarraCerrar14);
        BarraCerrar14.setLayout(BarraCerrar14Layout);
        BarraCerrar14Layout.setHorizontalGroup(
            BarraCerrar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar14)
                .addGap(26, 26, 26))
        );
        BarraCerrar14Layout.setVerticalGroup(
            BarraCerrar14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraCerrar14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelCerrar14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddTrabajadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(ModificarTrabajadorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(EliminarTrabajadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(BarraCerrar14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddTrabajadorButton, EliminarTrabajadorButton, ModificarTrabajadorButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarraCerrar14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTrabajadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarTrabajadorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModificarTrabajadorButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddTrabajadorButton, EliminarTrabajadorButton, ModificarTrabajadorButton});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddTrabajadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTrabajadorButtonActionPerformed
        
        UsuarioTextField.setText("");
        TelefonoTextField.setText("");
        NombreTextField.setText("");
        ApellidosTextField.setText("");
        SalarioTextField.setText("");
        PasswordTextField.setText("");
        jDialogAddTrabajador.setVisible(true);
        
    }//GEN-LAST:event_AddTrabajadorButtonActionPerformed

    private void BarraCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrarMousePressed

    private void BarraCerrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrarMouseDragged
        jDialogAddTrabajador.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrarMouseDragged

    private void LabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarMouseClicked
        jDialogAddTrabajador.setVisible(false);
    }//GEN-LAST:event_LabelCerrarMouseClicked

    private void LabelAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptarMouseClicked
        
        
        if(UsuarioTextField.getText() == "" || TelefonoTextField.getText() == "" || SalarioTextField.getText() == "" || NombreTextField.getText() == "" || ApellidosTextField.getText() == "" || PasswordTextField.getText() == ""){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        }else if(metodos.validarMovil(TelefonoTextField.getText()) == false){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir un número de telefono válido");
            TelefonoTextField.setText("");
        }else if(metodos.isNumeric(SalarioTextField.getText().replaceAll("\\.", "")) == false){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir un salario válido");
            SalarioTextField.setText("");
        }else{
            try {
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            String usuario = UsuarioTextField.getText();
            String telefono = TelefonoTextField.getText();
            String sal = SalarioTextField.getText();
            String nombre = NombreTextField.getText();
            String apellidos = ApellidosTextField.getText();
            String cargo = "Cuidador";
            String pass = metodos.passMD5(PasswordTextField.getText());
            String especialidad = EspecialidadComboBox.getSelectedItem().toString();
            
            float salario = Float.parseFloat(sal);
            int tlf = Integer.parseInt(telefono);
            Statement st = conn.createStatement(); 
            String sql = metodos.insertarCuidador(usuario, tlf, salario, nombre, apellidos, cargo, especialidad, pass);
            int resultado = st.executeUpdate(sql);
            
            if (resultado > 0) {
                
                sql = "SELECT * FROM personas WHERE cargo='Cuidador'";
                ResultSet rs = st.executeQuery(sql);
                DefaultTableModel tabla = (DefaultTableModel) TablaTrabajadores.getModel();

                while(tabla.getRowCount()>0){
                    tabla.removeRow(0);
                }

                while(rs.next()){
                    
                    String s = String.valueOf(rs.getFloat("salario")) + "€";

                    tabla.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("apellidos"),
                    rs.getInt("telefono"),s,rs.getString("especialidad")});


                }
                    JOptionPane.showMessageDialog(null, "Cuidador registrado correctamente");
                    jDialogAddTrabajador.dispose();

                
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Ha habido un error registrando a la persona, prueba de nuevo");
                UsuarioTextField.setText("");
                TelefonoTextField.setText("");
                SalarioTextField.setText("");
                NombreTextField.setText("");
                ApellidosTextField.setText("");
                PasswordTextField.setText("");
                
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_LabelAceptarMouseClicked

    private void ModificarTrabajadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTrabajadorButtonActionPerformed
        
        
        if (TablaTrabajadores.getSelectedRow() <= -1) {
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes seleccionar 1 fila");
        }else{
            
            DefaultTableModel tabla = (DefaultTableModel) TablaTrabajadores.getModel();
            String nombre = String.valueOf(tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 1));
            String apellidos = String.valueOf(tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 2));
            int telefono = (int) tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 3);
            String salario =  String.valueOf(tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 4));
            String especialidad = String.valueOf(tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 5));
            salario = salario.replaceAll("€", "");
            float sal = Float.parseFloat(salario);
            
            UsuarioTextField1.setText(nombre);
            TelefonoTextField1.setText(String.valueOf(telefono));
            SalarioTextField1.setText(String.valueOf(sal));
            NombreTextField1.setText(nombre);
            ApellidosTextField1.setText(apellidos);
            EspecialidadComboBox1.setSelectedItem(especialidad);
            
            jDialogEditarTrabajador.setVisible(true);
            
        }
        
    }//GEN-LAST:event_ModificarTrabajadorButtonActionPerformed

    private void LabelCerrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar1MouseClicked
        
        jDialogEditarTrabajador.dispose();
        
    }//GEN-LAST:event_LabelCerrar1MouseClicked

    private void LabelAceptar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelAceptar1MouseClicked
        if(UsuarioTextField1.getText() == "" || TelefonoTextField1.getText() == "" || SalarioTextField1.getText() == "" || NombreTextField1.getText() == "" || ApellidosTextField1.getText() == ""){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes rellenar todos los campos");
        }else if(metodos.validarMovil(TelefonoTextField1.getText()) == false){
            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir un número de telefono válido");
            TelefonoTextField1.setText("");
        }else if(metodos.isNumeric(SalarioTextField1.getText().replaceAll("\\.", "")) == false){

            JOptionPane.showMessageDialog(null, "¡ERROR! Debes introducir un salario válido");
            SalarioTextField1.setText("");
        }else{
            try {
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            DefaultTableModel tabla = (DefaultTableModel) TablaTrabajadores.getModel();
            String id = String.valueOf(tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 0));

            
            String usuario = UsuarioTextField1.getText();
            String telefono = TelefonoTextField1.getText();
            String sal = SalarioTextField1.getText();
            String nombre = NombreTextField1.getText();
            String apellidos = ApellidosTextField1.getText();
            String especialidad = EspecialidadComboBox1.getSelectedItem().toString();
            
            float salario = Float.parseFloat(sal);
            int tlf = Integer.parseInt(telefono);
            
            String sql = "UPDATE personas SET usuario='"+usuario+"',telefono="+tlf+",salario="+salario+",nombre='"+nombre+"',apellidos='"+apellidos+"',especialidad='"+especialidad+"' WHERE id="+id;
            int resultado = st.executeUpdate(sql);
            
            if (resultado > 0) {
                
                sql = "SELECT * FROM personas WHERE cargo='Cuidador'";
                ResultSet rs = st.executeQuery(sql);

                while(tabla.getRowCount()>0){
                    tabla.removeRow(0);
                }
                
                
                while(rs.next()){
                    
                    String s = String.valueOf(rs.getFloat("salario")) + "€";

                    tabla.addRow(new Object[]{rs.getInt("id"),rs.getString("nombre"),rs.getString("apellidos"),
                    rs.getInt("telefono"),s,rs.getString("especialidad")});


                }
                    JOptionPane.showMessageDialog(null, "Cuidador editado correctamente");
                    jDialogAddTrabajador.dispose();

                
                
            }else{
                
                JOptionPane.showMessageDialog(null, "Ha habido un error editando a la persona, prueba de nuevo");
                UsuarioTextField.setText("");
                TelefonoTextField.setText("");
                SalarioTextField.setText("");
                NombreTextField.setText("");
                ApellidosTextField.setText("");
                PasswordTextField.setText("");
                
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        
    }//GEN-LAST:event_LabelAceptar1MouseClicked

    private void BarraCerrar1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar1MouseDragged
        jDialogEditarTrabajador.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrar1MouseDragged

    private void BarraCerrar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar1MousePressed

    private void UsuarioTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextField1ActionPerformed

    private void EliminarTrabajadorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTrabajadorButtonActionPerformed
        
        try {
            DefaultTableModel tabla = (DefaultTableModel) TablaTrabajadores.getModel();
            int id = (int) tabla.getValueAt(TablaTrabajadores.getSelectedRow(), 0);
            String stringId = String.valueOf(id);
            String sql = "DELETE FROM personas WHERE id="+stringId;
            Conexion c = new Conexion("servidor.choto.es","3306","alu_Juanma_zoo1","unalumno","soyunalumno2022");
            Connection conn = c.makeConnect();
            Statement st = conn.createStatement();
            int resultado = st.executeUpdate(sql);
            if (resultado > 0) {
                tabla.removeRow(TablaTrabajadores.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Se ha eliminado al cuidador exitosamente");
            }else{
                JOptionPane.showMessageDialog(null, "No se ha podido eliminar al cuidador");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Trabajadores.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_EliminarTrabajadorButtonActionPerformed

    private void LabelCerrar14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrar14MouseClicked

        this.dispose();
    }//GEN-LAST:event_LabelCerrar14MouseClicked

    private void BarraCerrar14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar14MouseDragged
        this.setLocation(evt.getXOnScreen()-x, evt.getYOnScreen()-y);
    }//GEN-LAST:event_BarraCerrar14MouseDragged

    private void BarraCerrar14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraCerrar14MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraCerrar14MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabajadores().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTrabajadorButton;
    private javax.swing.JTextField ApellidosTextField;
    private javax.swing.JTextField ApellidosTextField1;
    private javax.swing.JPanel BarraCerrar;
    private javax.swing.JPanel BarraCerrar1;
    private javax.swing.JPanel BarraCerrar14;
    private javax.swing.JButton EliminarTrabajadorButton;
    private javax.swing.JComboBox<String> EspecialidadComboBox;
    private javax.swing.JComboBox<String> EspecialidadComboBox1;
    private javax.swing.JLabel LabelAceptar;
    private javax.swing.JLabel LabelAceptar1;
    private javax.swing.JLabel LabelCerrar;
    private javax.swing.JLabel LabelCerrar1;
    private javax.swing.JLabel LabelCerrar14;
    private javax.swing.JButton ModificarTrabajadorButton;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JTextField NombreTextField1;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JTextField SalarioTextField;
    private javax.swing.JTextField SalarioTextField1;
    private javax.swing.JTable TablaTrabajadores;
    private javax.swing.JTextField TelefonoTextField;
    private javax.swing.JTextField TelefonoTextField1;
    private javax.swing.JTextField UsuarioTextField;
    private javax.swing.JTextField UsuarioTextField1;
    private javax.swing.JDialog jDialogAddTrabajador;
    private javax.swing.JDialog jDialogEditarTrabajador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
